name: CI

on:
  pull_request:
    branches: ['master', 'develop']

jobs:
  build:
    run-on: ubuntu-latest

    steps:
      - name: Descargar el proyecto
        uses: actions/checkout@v3
      - name: Instalando Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'